### ISSUE TITLE
代码运行结果错误

### ISSUE THREAD

**Issue by Dolphin-wang** [TL-UESTC/RUL-prediction-with-Transformer#1]
作者您好，我运行了您上传的代码，使用了python validation_cmapss.py --source FD001 --target FD002 指令，但是结果与论文结果差异较大，平均RMSE为53.0174，请问是上传代码中哪里存在错误吗，谢谢！

**Comment by xinyao326** [comment]
Thanks for your attention! The issue is most likely caused by incompatible PyTorch version. Please strictly use pytorch==1.10 and torchvision==0.11.0.
