### ISSUE TITLE
Using Dataset Issues

### ISSUE THREAD

**Issue by abcyyy** [TL-UESTC/RUL-prediction-with-Transformer#3]
The data in the original C-MAPSS dataset "test-FD00X. txt" and "RUL_FD00X. txt", namely the test data from the original dataset, were not used in this experiment. Instead, only the data from the training set, namely "train-FD00X. txt", were used for training. However, the training target domain samples were still used for subsequent testing. Is this not considered as sample information leakage?

**Comment by abcyyy** [comment]
When evaluating the model, i.e. "validation_cmpass. py", the target domain data participating in the training is still used.

**Comment by abcyyy** [comment]
Is the dataset used for the results in Table 3 the training and testing sets divided in the "save/" file? Or use the training and testing sets divided by the original dataset? The former is equivalent to only training data from the original dataset.

**Comment by xinyao326** [comment]
domain adaptation is transductive, thus testing data overlaps with training data
